version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.11.0
  python: circleci/python@3.8.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python@3.8.1
    steps:
      - checkout
      - run: docker build . --tag $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/dogdict

  test:
    docker:
      - image: cimg/python@3.8.1
    steps:
      - checkout
      - run: python -m pytest --cov=api -v

  deploy:
    docker:
      - image: cimg/python@3.8.1
    steps:
      - checkout
      - run: 

  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          context: dogdict
      - deploy
          requires:
            - build
  aws_cli:
    jobs:
      - aws-cli-cred-setup:
          context: dogdict