version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: mmouru
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . --tag dogdict-app
  test:
    docker:
      - image: cimg/python:3.8.1
        auth:
          username: mmouru
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: cd db && coverage run -m pytest && coverage report --fail-under=99

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build